---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
        - name: secret-test
          image: shashankfrost/dummy:mongodb
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: test

            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb-cred
                  key: host

            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: mongodb-cred
                  key: port

            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-cred
                  key: username

            - name: MONGODB_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb-cred
                  key: password

            - name: MONGODB_AUTH_DB
              valueFrom:
                secretKeyRef:
                  name: mongodb-cred
                  key: auth_db
#            - name: MYSQL_HOST
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-cred
#                  key: host
#
#            - name: MYSQL_PORT
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-cred
#                  key: port
#
#            - name: MYSQL_USER
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-cred
#                  key: username
#
#            - name: MYSQL_PWD
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-cred
#                  key: password

      imagePullSecrets:
        - name: sha-docker-secret
